[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quinn = "*"
rustls = { version = "0.21.2", features = ["dangerous_configuration", "quic"] }